FROM node:lts-alpine3.14
# ENV NODE_ENV production
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn
RUN yarn build menu
RUN yarn cache clean
COPY dist/apps/menu/ /usr/src/app/
EXPOSE 3000
CMD ["node", "main.js"]