FROM node:lts-alpine3.14
WORKDIR /usr
COPY package*.json ./
COPY yarn.lock ./
RUN yarn
COPY . .
RUN yarn build menu

FROM node:lts-alpine3.14
WORKDIR /usr/app
ENV NODE_ENV production
COPY package.json ./
RUN yarn
COPY --from=0 /usr/dist/apps/menu/ .
EXPOSE 3000
CMD ["node", "main.js"]